title: "Blog Cyber de Hourso"
description: "Mes labs, mes recherches et mes apprentissages en cybersécurité."
url: "https://hourso.github.io"
baseurl: ""

# --- Thème ---
remote_theme: "mmistakes/minimal-mistakes"

# Langue du site
locale: "fr-FR"

# Auteur
author:
  name: "Hourso"
  bio: "Passionné de cybersécurité (AD, SOC, IAM, Samba, etc.)."
  location: "France"
  links:
    - label: "GitHub"
      icon: "fab fa-github"
      url: "https://github.com/hourso"

# Mise en page de base
layout: single

# Activer les posts
paginate: 5
paginate_path: "/page:num/"

# Plugins (supportés par GitHub Pages)
plugins:
  - jekyll-seo-tag
  - jekyll-paginate
