title: "Blog Cyber de Hourso"
description: "Labs, recherches et apprentissages en cybersécurité."
url: "https://hourso.github.io"
baseurl: ""

remote_theme: "mmistakes/minimal-mistakes"
minimal_mistakes_skin: "default"

locale: "fr-FR"

author:
  name: "Hourso"
  bio: "Cybersécurité : AD, SOC, IAM, labs…"
  links:
    - label: "GitHub"
      icon: "fab fa-github"
      url: "https://github.com/hourso"

permalink: /:categories/:title/

paginate: 5
paginate_path: "/page:num/"

plugins:
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-include-cache
